package:
  name: perl-sanger-cgp-vagrent
  version: '3.5.1'

source:
  url: https://github.com/cancerit/VAGrENT/archive/v3.5.1.tar.gz
  sha256: d8265a6a99c4608ff93c0661ddade3592bafe9f9b8c2adbeb6a47bbfad4ae8c9

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-module-build
    - perl-file-sharedir-install
    - perl-bio-db-hts
    - perl-sub-exporter-progressive
    - perl-set-intervaltree
  run:
    - perl
    - perl-bio-db-hts
    - perl-sub-exporter-progressive
    - perl-set-intervaltree

test:
  imports:
    - Sanger::CGP::Vagrent

about:
  home: https://github.com/cancerit/VAGrENT
  license: GPLv3
  summary: A toolset for comparing genomic variants to reference genome annotation to identify potential biological consequences
