{% set version = "0.3.6.1" %}
{% set sha256 = "7af43894d5e46bcfb4a95032144a2b1cf4438ac3ad105e8c95e1bd2a132d684c" %}

package:
  name: dashing
  version: {{ version }}

build:
  number: 0
  script: make dashing

source:
  url: https://github.com/dnbaker/dashing/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib
  run:
    - zlib

about:
  home: https://github.com/dnbaker/dashing
  license: GPL-3
  summary: Fast and accurate genomic distances using HyperLogLog


test:
  commands:
    - dashing --help


extra:
  identifiers:
    - doi:10.1101/501726
  recipe-maintainers:
    - silask
    - dnbaker
